### ISSUE TITLE
scripts for cleaning and moving files

### ISSUE THREAD

**Issue by sriramrudraraju** [sriramrudraraju/npm-package-template#3]
``` 
 "build": "yarn run clean && tsc",
 "postbuild": "ef-tspm && yarn run copy-files",
 "clean": "rimraf lib/",
 "prepare": "yarn run build",
 "copy-files": "copyfiles -u 1 src/**/*.js dist"
```
more [info](https://github.com/Microsoft/TypeScript/issues/30835)

**Comment by sriramrudraraju** [comment]
merged webpack support to move and clean. issue #4

**Comment by FredericLatour** [comment]
@sriramrudraraju Does this run under linux or Mac?

From my tests, this should work:
`
"copy-files": "copyfiles -u 1 \"src/**/*.js\" dist"
`

**Comment by sriramrudraraju** [comment]
I havent tested that.. I saw those scripts on few open source projects. but I decided i implement that feature using webpack, so that i dont need to worry about OS dependency
